### ISSUE TITLE
Staramr M. tuberculosis integration?

### ISSUE THREAD

**Issue by Takadonet** [phac-nml/staramr#112]
Hi,

This paper just came out with a new pointfinder database for M. tuberculosis:

"Improved Resistance Prediction in Mycobacterium tuberculosis by Better Handling of Insertions and
Deletions, Premature Stop Codons, and Filtering of Non-informative Sites"
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6834686/pdf/fmicb-10-02464.pdf

Database:
https://bitbucket.org/genomicepidemiology/pointfinder_db/src/master/mycobacterium_tuberculosis/

Staramr searches pointfinder databases, would it be possible to integrate this pointfinder database within staramr?

Thanks!
Dan

**Comment by dfornika** [comment]
Typo in your database link above. 

https://bitbucket.org/genomicepidemiology/pointfinder_db/src/master/mycobacterium_tuberculosis/

**Comment by Takadonet** [comment]
Thanks @dfornika

**Comment by charlottecc** [comment]
Hi, 

Would it also be possible to integrate _Staphylococcus aureus_ into the pointfinder database as well? 

Thanks! 
Charlotte

**Comment by Takadonet** [comment]
Closing issue since moved requests into #17
