### ISSUE TITLE
PlasmidFinder database

### ISSUE THREAD

**Issue by ireneortega** [phac-nml/staramr#120]
Staramr manual says "**By default, both databases are used**" for `--plasmidfinder-database-type`. How can I select both databases at the same time? I mean I want staramr to look for in _gram_positive_ and _enterobacteriaceae_ databases, not just one.

Thanks.

**Comment by apetkau** [comment]
Using both databases is the default behavior. So there's no need to pass anything on the command-line to select both of them.

**Comment by ireneortega** [comment]
All right, I understood. Now I got it! Thanks @apetkau
