### ISSUE TITLE
PointFinder - mutations in gyrA gene

### ISSUE THREAD

**Issue by evangelosmourkas** [phac-nml/staramr#131]
Hello,
I am using pointfinder in Campylobacter jejuni and Campylobacter coli genomes. The tool only identifies mutations in the gyrA gene in C.jejuni. Considering the common nature of this mutation in both those species I would expect to find it in many C.coli genomes. For the record, I have used >500 coli genomes and for some of them I have phenotypic data that show resistance to ciprofloxacin/nalidixic acid. I have tried it after updating the database too.
Any help/thought on this would be greatly appreciated!

**Comment by apetkau** [comment]
Hell @evangelosmourkas 

staramr uses the pointfinder database which will look for these specific mutations in gyrA for Campylobacter:

https://bitbucket.org/genomicepidemiology/pointfinder_db/src/8706a6363bb29e47e0e398c53043b037c24b99a7/campylobacter/resistens-overview.txt

That is the version of the file used as part of the default database for staramr (version `0.7.2`). The latest version of the pointfinder database would be https://bitbucket.org/genomicepidemiology/pointfinder_db/src/master/campylobacter/resistens-overview.txt. This looks pretty similar though, so would explain why updating the database has no effect.

If you submit your genomes to the ResFinder website do you get anything different (https://cge.cbs.dtu.dk/services/ResFinder/)? Unfortunately, as we do not maintain the ResFinder/PointFinder databases, there's not much other information I can give you about why you're not picking anything up for Campylobacter coli. You could try contacting the maintainers of ResFinder/PointFinder if you suspect something is missing.

Another option is to run your genomes through RGI/CARD (https://card.mcmaster.ca/analyze/rgi), which has it's own maintained database and could give you more information about what's going on. You an use the web tool I just linked to, but there's also a standalone version of RGI you can install via GitHub if you want to run it all yourself (https://github.com/arpcard/rgi)

I hope this helps you out.

**Comment by evangelosmourkas** [comment]
Hi @apetkau !

Thank you for getting back to me and for the suggestions.
I have already run the ResFinder, CARD and ncbi databases. I am interested in the pointfinder because I am after a specific mutation in that gene. 
It seems there is something going on with the Pointfinder database so I will chase it up there.
Again thank you for your help.

**Comment by apetkau** [comment]
No problem. Note that staramr is developed independently from ResFinder/PointFinder so I would make sure to run some of your genomes through the ResFinder website first just to check and make sure they aren't doing anything differently in their software. But it may just be that you have a specific mutation that's not accounted for in any of these databases.

**Comment by apetkau** [comment]
Also, if you're interested in comparing reports from different tools, this might be useful https://github.com/pha4ge/hAMRonization.
