### ISSUE TITLE
Genome length error

### ISSUE THREAD

**Issue by XtineLiu** [phac-nml/staramr#140]
How can I change the settings so that I don't get error "Genome length is not within the acceptable length range [4000000,6000000]". Because my input fasta of genomes fall outside the range. Thx

**Comment by apetkau** [comment]
Hello. You can use `--genome-size-lower-bound` and `--genome-size-upper-bound`.

**Comment by XtineLiu** [comment]
It worked! I did

staramr search -o out *.fasta --genome-size-lower-bound 1000000 --genome-size-upper-bound 9000000

Thx
