### ISSUE TITLE
Can;t install staramr, blast not found.

### ISSUE THREAD

**Issue by Abelcanc3rhack3r** [phac-nml/staramr#141]
I tried installing via mamba:

conda install mamba 
mamba install -c bioconda -c conda-forge -c defaults staramr==0.7.2 pandas==1.1.5 mlst==2.19.0

Then it gives this output:
Looking for: ['staramr==0.7.2', 'pandas==1.1.5', 'mlst==2.19.0']

bioconda/win-64                                             Using cache
bioconda/noarch                                             Using cache
conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache
pkgs/main/noarch                                              No change
pkgs/main/win-64                                              No change
pkgs/r/win-64                                                 No change
pkgs/msys2/win-64                                             No change
pkgs/r/noarch                                                 No change
pkgs/msys2/noarch                                             No change

Pinned packages:
  - python 3.8.*

Encountered problems while solving:
  - nothing provides blast >=2.2.31 needed by staramr-0.7.2-py_0
  - nothing provides blast >=2.9.0 needed by mlst-2.19.0-0

**Comment by apetkau** [comment]
Hello @Abelcanc3rhack3r 

From the `win-64` messages above, I am assuming you are trying to install starmar on Windows using conda? Unfortunately, `staramr` depends on packages found through the bioconda project (https://bioconda.github.io/index.html), which does not support Windows.

A few options you would have to install starmar on Windows would be:

1. Install the dependencies outside of conda (https://github.com/phac-nml/staramr#dependencies). This might require a lot of effort to get everything working though.
2. You could try out the Docker container found at https://quay.io/repository/biocontainers/staramr?tab=info (this is built automatically from the conda package).
3. You could try using Windows Subsystems for Linux (https://ubuntu.com/wsl) or a virtual machine to get a Linux environment installed on Windows, and then proceed through installing via conda above.

I hope this helps.

**Comment by Abelcanc3rhack3r** [comment]
Hi Aaron,
Yes I'm using Windows.



So you are saying I must Install everything on the Linux environment?

The mamba install command will take care of all the dependencies in the
Linux environment including the blast?

Thank you
