### ISSUE TITLE
Bioconda channel order

### ISSUE THREAD

**Issue by lenorakepler** [phac-nml/staramr#162]
This may be something specific to my configuration, but wanted to point out in case it helps anyone else.

I was having an issue installing a standalone staramr environment (for 0.9.1 or 0.7.2) with the command as suggested:
`mamba create -c bioconda -c conda-forge -c defaults --name staramr staramr==0.7.2 pandas==1.1.5 mlst==2.19.0`

This would result in the mamba error:
Encountered problems while solving:
  - package staramr-0.7.2-py_0 requires biopython >=1.70, but none of the providers can be installed

I read elsewhere that bioconda is strict about channel order, and if things are not installed in the order conda-forge > bioconda > defaults, it can cause issues, so I changed around the 'mamba create' command to:

`mamba create -c conda-forge -c bioconda -c defaults --name staramr staramr==0.7.2 pandas==1.1.5 mlst==2.19.0`

and was able to successfully create the environment.

Thanks for a fabulous tool!
Lenora

**Comment by apetkau** [comment]
Thanks so much for pointing this out @lenorakepler . This will be fixed in https://github.com/phac-nml/staramr/pull/163

**Comment by apetkau** [comment]
Fixed in https://github.com/phac-nml/staramr/pull/163
