### ISSUE TITLE
PlasmidFinder database enterobacteriaceae no longer an option

### ISSUE THREAD

**Issue by eam12** [phac-nml/staramr#169]
For the `--plasmidfinder-database-type` flag, it appears that enterobacteriaceae is no longer an option in PlasmidFinder 2.1. When you try to specify `enterobacteriaceae` you get the following message:

```
2023-03-09 15:35:58 INFO: PlasmidFinder database type [enterobacteriaceae] is out of date, switching to [enterobacteriales]
```

I think the `--help` message just needs to be updated to remove `enterobacteriaceae` as an option.

**Comment by apetkau** [comment]
Thanks for pointing this out. Yes, looks like we may have to update the help message here.
