### ISSUE TITLE
Add support for additional PointFinder organisms

### ISSUE THREAD

**Issue by apetkau** [phac-nml/staramr#17]
Only *salmonella* is supported from the PointFinder database.  Add support for all other organisms - https://bitbucket.org/genomicepidemiology/pointfinder_db/src

* [x] campylobacter
* [ ] e.coli
* [ ] gonorrhoeae
* [ ] tuberculosis
* [x] enterococcus faecalis
* [x] enterococcus faecium
* [ ] malaria
* [ ] [M. tuberculosis](https://bitbucket.org/genomicepidemiology/pointfinder_db/src/master/mycobacterium_tuberculosis/) 
* [ ]  [Staphylococcus aureus](https://bitbucket.org/genomicepidemiology/pointfinder_db/src/master/staphylococcus_aureus/)

**Comment by pimarin** [comment]
Hello,

I'm interested to integrate `staramr ` into a national project for antimicrobial research. We are developing a complete workflow for research and clinical use. If I can help to develop the tool to be more integrative in term of pointfinder database.
