### ISSUE TITLE
start and end position

### ISSUE THREAD

**Issue by vappiah** [phac-nml/staramr#176]
Hi Developers,
I need some clarification.  When STARAMR returns  plasmidfinder result like this
START  END
7385    7012

Does it mean the hit is found on the reverse strand?

I have attached a screen short of a report which STARAMR generated when I searched my sequences for plasmids
![Screenshot from 2023-05-19 22-43-28](https://github.com/phac-nml/staramr/assets/14283733/45b0ee7e-2a2a-4b31-91ee-3fcb4f4a2533)

**Comment by apetkau** [comment]
@vappiah yes, that's correct. If start is greater than end it means hit is on reverse strand.
