### ISSUE TITLE
The plasmidfinder.tsv shows that there is no plasmid present

### ISSUE THREAD

**Issue by qianxin-kxy** [phac-nml/staramr#178]
Hello, I used the following code to predict plasmids for hundreds of strains of Acinetobacter baumannii, 

_$ staramr search --plasmidfinder-database-type enterobacteriales -o out *.fasta_

but the plasmidfinder.tsv only showed the following prompt
_Isolate ID	Plasmid	%Identity	%Overlap	HSP Length/Total Length	Contig	Start	End	Accession_
 and did not display a single plasmid. I don't know what to do

**Comment by qianxin-kxy** [comment]
Thank you for your reply and suggestions,
I have tried the first two methods, and the result of the first one also shows that there are none(The genome of the strain I am using is a FASTA file assembled using SPAdes after second-generation sequencing);

The second method, I also encountered new problems and was unable to run successfully. I have already provided feedback to the author and am waiting for their response;

As for the third method, I plan to first find a strain of Acinetobacter containing plasmids on NCBI and try it out. I will tell you the results later when I have them

**Comment by apetkau** [comment]
I am closing this issue for now.
