### ISSUE TITLE
Duplicated resfinder hits with update to database

### ISSUE THREAD

**Issue by kimyoungw** [phac-nml/staramr#180]
Hi,

We're getting duplicated resfinder hits on the same contig, one with unknown under Predicted Phenotype and then another with the predicted phenotype. This appears to only happen when we update the resfinder database to one of the most recent commits. Older/default versions of the database don't have this issue.

![image](https://github.com/phac-nml/staramr/assets/112518496/b8ae72b7-9aae-4356-aee3-1212150bae7b)

We're running staramr in a singularity container built into nextflow: docker://staphb/staramr:0.7.1
Singularity params:
`-B $PWD:/data`
`--cleanenv`
`--no-home`

Commands run in container:
`staramr db update --resfinder-commit ${params.staramr_resfinder_commit} --pointfinder-commit ${params.staramr_pointfinder_commit} --plasmidfinder-commit ${params.staramr_plasmidfinder_commit} databases`

`staramr search --database databases --pid-threshold 90 --percent-length-overlap-resfinder 50 --no-exclude-genes -o "staramr" ${shovill_contigs}`

Any help is much appreciated.

**Comment by apetkau** [comment]
What is the resfinder database commit you are using where the issue occurs? It might be the case there are duplicated entries in some commits of the database.

**Comment by kimyoungw** [comment]
staramr_resfinder_commit = '1a53e55081ce35dfc05ecd995e6326eb8c428b19' //Date of commit: Wed, 31 May 2023 08:34
	staramr_pointfinder_commit = 'cb7806fd9bfeec1497ff9f6b6c278284ba560ec6' //Date of commit: Wed, 31 May 2023 08:37
	staramr_plasmidfinder_commit = '314d85f43e4e018baf35a2b093d9adc1246bc88d' //Date of commit: Fri, 17 Mar 2023 08:05

These are the commits.

**Comment by kimyoungw** [comment]
oops didn't mean to close

**Comment by kimyoungw** [comment]
Thank you for the prompt reply and thorough explanation. Yea we're using 0.7.1 because it's the only containerized version that works for us at the moment :l But yes, will definitely try to see if the database commits you suggested resolve our issues. Thanks again! Closing this issue.
