### ISSUE TITLE
cant run staramr

### ISSUE THREAD

**Issue by Hedi65** [phac-nml/staramr#181]
dear community 

im trying to run staramr but for some reason staramr give me an error saying my fasta file does not exist. 

here is my command line: staramr search -o test myfile.fasta

I'm sure no misspelling occurred while typing the path and file name. 

thanks for your input

**Comment by apetkau** [comment]
Another possibility, if you are running in a container like Docker, is that the file does not exist within the container. In this case, you may need to mount the current directory as a volume and use full paths. For example:

```
docker run -v $PWD:$PWD staramr-image:lastest staramr -o $PWD/test $PWD/myflie.fasta
```

(`$PWD` contains the current working directory).

**Comment by apetkau** [comment]
Closing this issue. If it is has still remained unresolved feel free to re-open.
