### ISSUE TITLE
Adding more databases

### ISSUE THREAD

**Issue by joao1980** [phac-nml/staramr#209]
Hi, 
Thanks for the tool and will definitely give it a try. I was wondering thoug if it would be possible to add more information from other databases (e.g., NanoARG, CARD, MEGARes)? Or is the merging of information from these databses incompatible with the current structure?
Cheers!

**Comment by apetkau** [comment]
Hello @joao1980,

Sorry for the late reply. It would not be possible without a lot of work to add additional databases (e.g., NanoARG, CARD, etc). It would be best to run the respective software that interact with these databases and compile results together.

Aaron
