### ISSUE TITLE
Add to GRDI-AMR.com

### ISSUE THREAD

**Issue by chapb** [phac-nml/staramr#211]
Was development related to the GRDI-AMR1 or GRDI-AMR2 projects?

If so, would you mind if I linked to this project from https://grdi-amr.com?

**Comment by apetkau** [comment]
Hello Brennan. Yes, development of StarAMR is related to the GRDI-AMR2 project. So you can link to staramr on the website.

**Comment by chapb** [comment]
Thanks!
