### ISSUE TITLE
`np.unicode_` was removed in the NumPy 2.0 release

### ISSUE THREAD

**Issue by sgsutcliffe** [phac-nml/staramr#213]
We need to replace `np.unicode_` with `np.str_` in [line](https://github.com/phac-nml/staramr/blob/d8370b70b83f08711d53421d10d06a4cee369af5/staramr/blast/results/BlastResultsParser.py#L96) 

```
dtype={'qseqid': np.unicode_, 'sseqid': np.unicode_})
```

In the `BlastResultsParser.py` script to be compatible with 2.0+ Numpy

**Comment by cizydorczyk** [comment]
I had to manually edit this line as stated above to make staramr run. I have python 3.12.5 and numpy 2.1.0 installed. Staramr 0.10.0.

**Comment by apetkau** [comment]
Fixed in https://github.com/phac-nml/staramr/pull/217
