### ISSUE TITLE
Incorporation of plasmids in final report

### ISSUE THREAD

**Issue by apetkau** [phac-nml/staramr#46]
Incorporation of plasmids in final `summary.tsv`. That is `summary.tsv` should look like:

| Isolate ID | Genotype  | Predicted Phenotype | Plasmid Genes |
|-------------|---------------|----------------------------|---------------------|
| SRR1952908 | aadA1, blaTEM-57 | streptomycin | IncX1, IncFIB(S) |

**Comment by jennifertran** [comment]
Issue resolved in the merge request, the issue is now closed.
