### ISSUE TITLE
Construct new report incorporating resistance genes and plasmids

### ISSUE THREAD

**Issue by apetkau** [phac-nml/staramr#47]
This report should incorporate both resistance genes and plasmids, but unlike `summary.tsv`, each resistance gene/plasmid should be on a separate line of the table.

**Comment by jennifertran** [comment]
Got feedback from Laura, she says:

 - Each isolate tested should have the datatype `plasmid or resistance` marked
        - **If none exist** then the `gene` would indicate `None`

**Comment by jennifertran** [comment]
Issue has been resolved/implemented
