### ISSUE TITLE
Update documentation for staramr to include plasmidfinder

### ISSUE THREAD

**Issue by apetkau** [phac-nml/staramr#55]
Update the documentation in the `README.md` to include plasmidfinder. That is, we should add:

* [x] - An example of the **PlasmidFinder** results table and the **Detailed_Summary** table.
* [x] - A description of the columns in these tables.
* [x] - Update the tutorial to include desciptions of detecting plasmids.
* [x] - Update the usage docs to reflect new command-line parameters for `staramr`.

**Comment by jennifertran** [comment]
Merged
