### ISSUE TITLE
Revert ResFinder/PointFinder default to previous release versions

### ISSUE THREAD

**Issue by apetkau** [phac-nml/staramr#61]
Revert ResFinder/PointFinder default databases to previous release versions for this next release.  That is, back to versions found in [staramr 0.4.0](https://github.com/phac-nml/staramr/blob/0.4.0/staramr/databases/AMRDatabasesManager.py#L14).

My reason for this is our mapping between the AMR gene and drug resistance is only completed for these ResFinder/PointFinder database versions.

This would likely involve disabling support for *enterococcus faecalis* (https://github.com/phac-nml/staramr/pull/35) since I don't believe this is available in the earlier PointFinder database.

Support will be re-added in a later release.

**Comment by jennifertran** [comment]
Closing Issue as it's been resolved
