### ISSUE TITLE
Add color logging to Staramr

### ISSUE THREAD

**Issue by jennifertran** [phac-nml/staramr#68]
There's currently a library called [colored logs](https://pypi.org/project/coloredlogs/) which is a python library that output colors in the terminal. I think this would be really helpful especially for debugging code in the project. 

Example:

![image](https://user-images.githubusercontent.com/11945573/56041459-69eb7d00-5cfe-11e9-9f1c-93543b28d31a.png)

**Comment by apetkau** [comment]
That looks really cool :+1:

**Comment by jennifertran** [comment]
Closing issue as this have been implemented
