### ISSUE TITLE
Auto-fit width of column in Excel spreadsheet

### ISSUE THREAD

**Issue by peterk87** [phac-nml/staramr#7]
The Excel spreadsheet looks great! The freezing of panes is nice and so is having all the parameters used to run `staramr` under its own sheet. 

I would recommend one enhancement: auto-fitting the column widths to the contents of each column for readability (and since users will likely do it themselves anyway). 

So after you create a worksheet in the workbook, iterate through each column in the `df` and adjust the corresponding column's width in the worksheet:

```python
df.to_excel(writer, sheet_name=fixed_sheetname, **pd_to_excel_kwargs)
worksheet = writer.book.get_worksheet_by_name(fixed_sheetname)
for i, width in enumerate(get_col_widths(df, index=args.write_index)):
    worksheet.set_column(i, i, width)
```

where `get_col_widths` is:
```python
def get_col_widths(df, index=False):
    """Calculate column widths based on column headers and contents"""
    if index:
        idx_max = max([len(str(s)) for s in df.index.values] + [len(str(df.index.name))])
        yield idx_max
    for c in df.columns:
        # get max length of column contents and length of column header
        yield np.max([df[c].astype(str).str.len().max(), len(c)])
```

It's not perfect (assumes uniform character length), but might save users some time.

**Comment by apetkau** [comment]
Thanks @peterk87 this is awesome.  Really helpful.

**Comment by peterk87** [comment]
Great to hear that it was helpful for you :-)

**Comment by apetkau** [comment]
Done in https://github.com/phac-nml/staramr/pull/16
