### ISSUE TITLE
Rename "Plasmid Genes" column

### ISSUE THREAD

**Issue by apetkau** [phac-nml/staramr#75]
It looks like the **PlasmidFinder** web server lists the plasmid incompatibility factors under a column named **Plasmid**:

![image](https://user-images.githubusercontent.com/200517/56695274-3e797280-66ae-11e9-9e8c-7dd9dbee4371.png)

We should maybe look at renaming the column **Plasmid Genes** in staramr to **Plasmid** to avoid confusion (or is there a better name?)

![image](https://user-images.githubusercontent.com/200517/56695349-72ed2e80-66ae-11e9-923c-fc29102abe5c.png)

**Comment by apetkau** [comment]
In addition to rename in the `summary` table, please rename:

* **Gene** -> **Plasmid** in the `PlasmidFinder` table
* **Gene** -> **Gene/Plasmid** in the `Detailed_Summary` table

**Comment by jennifertran** [comment]
Closing issue as this has been merged
