### ISSUE TITLE
Add MLST results to Detailed_Summary

### ISSUE THREAD

**Issue by jennifertran** [phac-nml/staramr#87]
Rename **Genes/Plasmids** to **Genome Matches**. Incorporate the MLST data to the detailed summary using the following format: Where the highlighted text should be in the form of `ST19 (senterica)`

![image](https://user-images.githubusercontent.com/11945573/62147077-5fa8bb00-b2bc-11e9-8d5b-2f4883e05a40.png)

**Comment by apetkau** [comment]
Fixed in #88
