### ISSUE TITLE
Pointfinder-Campylobacter 

### ISSUE THREAD

**Issue by haan12345** [phac-nml/staramr#95]
It keeps showing only supported database is 'Salmonella'. so Campylobacter db for pointfinder is not available currently?

**Comment by apetkau** [comment]
The `campylobacter` pointfinder database should work. Which version of staramr are you running?

**Comment by haan12345** [comment]
I am using starmar 0.3.0

**Comment by haan12345** [comment]
can be a dumb question.. but how i upgrade under conda environment?

**Comment by haan12345** [comment]
I got it! Thank you so much for help!!

**Comment by apetkau** [comment]
No problem. You're welcome.
