### ISSUE TITLE
Missing --output-mlst

### ISSUE THREAD

**Issue by apetkau** [phac-nml/staramr#99]
It looks like the parameter `--output-mlst` was missed in release `0.6.0`. This should allow you to specify an output file for the MLST results, similar to `--output-plasmidfinder`.

See line https://github.com/phac-nml/staramr/blob/2d882b4547e4838c368391be8a3679d445bdc793/staramr/subcommand/Search.py#L133

**Comment by jennifertran** [comment]
This is abit strange, I was sure I did add the `--output-mlst` command at some point. If you were to look in the development branch, the command for mlst is there https://github.com/phac-nml/staramr/blob/development/staramr/subcommand/Search.py#L145

**Comment by Takadonet** [comment]
Been fixed in version 0.6.1
